spring:
  profiles.active: dev
---
spring:
  profiles: dev
logging:
  file: logs/dev_app.log
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    org.springframework.web: DEBUG
    guru.springframework.controllers: DEBUG
    org.hibernate: DEBUG
---
spring:
  profiles: production
logging:
  file: logs/production_app.log
  pattern:
    file: "%d %-5level [%thread] %logger{0} : %msg%n"
  level:
    org.springframework.web: WARN
    guru.springframework.controllers: WARN
    org.hibernate: WARN